use_frameworks!

target 'SwiftRadioPlayer_ios' do
  platform :ios, '10.0'
  pod 'SwiftRadioPlayer', :path => '../'

  target 'SwiftRadioPlayer_Tests' do
    inherit! :complete

  end
end

target 'SwiftRadioPlayer_SwiftUI' do
  platform :ios, '14.0'
  pod 'SwiftRadioPlayer', :path => '../'
end

target 'SwiftRadioPlayer_mac' do
  platform :osx, '10.12'
  pod 'SwiftRadioPlayer', :path => '../'
end

target 'SwiftRadioPlayer_tvOS' do
  platform :tvos, '10.0'
  pod 'SwiftRadioPlayer', :path => '../'
end
