use_frameworks!

target 'FRadioPlayer_ios' do
  platform :ios, '10.0'
  pod 'FRadioPlayer', :path => '../'

  target 'FRadioPlayer_Tests' do
    inherit! :search_paths

  end
end


target 'FRadioPlayer_mac' do
  platform :osx, '10.12'
  pod 'FRadioPlayer', :path => '../'
end
