name: FRadioPlayerDemo
options:
  deploymentTarget:
    iOS: 14.0
packages:
  FRadioPlayer:
    path: ../
targets:
  FRadioPlayerDemo:
    type: application
    platform: iOS
    sources:
      - path: FRadioPlayerDemo
    dependencies:
      - package: FRadioPlayer
        product: FRadioPlayer
    settings:
      INFOPLIST_FILE: FRadioPlayerDemo/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.fethica.fradioplayerdemo
    scheme:
      shared: true
