name: SPM

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (SwiftPM)
        run: swift build -v
      - name: Test (SwiftPM)
        run: swift test -v

